apiVersion: v1
kind: Pod
metadata:
  name: portfolio-app
  labels: 
    name: portfolio-app
spec:
  containers:
  - name: portfolio
    image: sudeshsurve/portfolio:latest
    ports:
    - containerPort: 80
 