apiVersion: v1
kind: Service
metadata:
  name: portfolio-app-service
spec:
  type: NodePort  
  selector:
    app: portfolio-app
  ports:
    - port: 7000
      targetPort: 80
      nodePort: 30002             